# Generated by Django 3.1.3 on 2020-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='proportion',
            field=models.FloatField(default=0),
        ),
    ]
