# Generated by Django 3.1.3 on 2020-12-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_proportion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='proportion',
            field=models.IntegerField(default=0),
        ),
    ]
